repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-tabs

  - repo: https://github.com/kintoandar/pre-commit.git
    rev: v2.1.2
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
